### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by xy928** [hecoter/H_m3u8DL#1]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.key"
#EXTINF:4.000000,
这种的没法下载

**Comment by xy928** [comment]
> #EXTM3U #EXT-X-VERSION:3 #EXT-X-TARGETDURATION:5 #EXT-X-MEDIA-SEQUENCE:0 #EXT-X-KEY:METHOD=AES-128,URI="key.key" #EXTINF:4.000000, 这种的没法下载http://node4.mtvideo1.xyz/csp/20211210/ZP4IMAfHap/index.m3u8

**Comment by hecoter** [comment]
`from m3u8download_hecoter import m3u8download
m3u8download(m3u8url='https://hls.videocc.net/4adf37ccc0/a/4adf37ccc0342e919fef2de4d02b473a_3.m3u8',title='9-第四节  民法典合同编及价格法（二）',work_dir='000',key='kQ2aSmyG1FDSmzpqTso/0w==',enable_del=False)
`
需自己输入已经解密的key

**Comment by xy928** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发送的邮件已收到。。。。。。。

**Comment by xy928** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发送的邮件已收到。。。。。。。
