### ISSUE TITLE
如何带headers下载

### ISSUE THREAD

**Issue by 82318179** [hecoter/H_m3u8DL#2]
如何带headers下载
给的例子中，没有 headers 呢？我的 M3U8 不带 headers 无法下载。

**Comment by 82318179** [comment]
还有您这个 key = 后面是16进制的key 么？
    m3u8download(m3u8url=m3u8_url, title='test', base_uri_parse=base_url, work_dir='000', threads=1, key='B69F4BB086271A1628FFEC1D2952DF8F', headers=headers, enable_del=False)
我这样下载以后， 为什么下载的ts 都没有解密呢？我的key就是 16进制的key字符串呀。
没有解密，也没有合并。

**Comment by hecoter** [comment]
更新了说明文件，可以再看下
key 支持多种形式
没有解密说明key是错的
把 enable_del 改成 True或者不写这个参数都可以自动删除多余文件
