### ISSUE TITLE
报错信息proxy和SSL报错，希望添加参数排除错误

### ISSUE THREAD

**Issue by jianala** [hecoter/H_m3u8DL#4]
证书 SSLError错误，需要在源码download():->requests中添加verify=False，另外添加的代理也总是报错

报错信息如下：
HTTPSConnectionPool(host='*****', port=443): Max retries exceeded with url: /****/64925727.ts (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

**Comment by jianala** [comment]
Don't use version 1.26.0, install a lower version using this command:

pip install urllib3==1.25.11

google 写的解决报错办法

**Comment by hecoter** [comment]
下载新版文件测试，已解决  `pip install H_m3u8DL`
